# Generated by Django 3.0.7 on 2020-06-07 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipped_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Itemlist')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Userstatus')),
            ],
            options={
                'unique_together': {('uid', 'iid')},
            },
        ),
        migrations.CreateModel(
            name='Itemlist_monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weapon', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Useritem',
        ),
        migrations.AlterField(
            model_name='monsterstatus',
            name='itemid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Itemlist_monster'),
        ),
    ]
