# Generated by Django 3.0.7 on 2020-06-07 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200607_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='equipped_item',
        ),
    ]
