# Generated by Django 3.0.7 on 2020-06-07 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_equipped_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemlist_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weapon', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Itemstatus_monster',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Itemlist_monster')),
                ('price', models.IntegerField()),
                ('itemlevel', models.IntegerField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Itemstatus_store',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Itemlist_store')),
                ('price', models.IntegerField()),
                ('itemlevel', models.IntegerField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
