# Generated by Django 3.0.7 on 2020-06-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200608_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='damage',
            field=models.IntegerField(default=0),
        ),
    ]
